baseURL: "https://www.bkjha.com/"
title: bkjha.com
paginate: 8
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About
          url: about
          weight: 5
        - name: Blog
          url: posts
          weight: 5
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        # - name: Categories
        #   url: categories/
        #   weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # description: ""
  author: Bal Krishna Jha
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  # comments: false
  hidemeta: false
  tocopen: true
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: Hi 👋🏼
    subtitle: "Musafir hu yaro, na ghar hai na thikana"
    imageUrl: "#"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Blog
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi 👋🏼"
    Content: >
      Welcome. Swagat. 


  socialIcons:
    - name: github
      url: "https://github.com/chrishna1/"
    # - name: RSS
    #   url: "index.xml"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/7699859"
    - name: linkedin
      url: "https://www.linkedin.com/in/bal-krishna-jha/"
    - name: twitter
      url: "https://twitter.com/80_ghat"
    - name: email
      url: "mailto:adjnct+site@gmail.com"
    # - name: gitlab
    #   url: "index.xml"

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35
  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"
  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"
  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page
  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
